/*
 version 3.4.179
*/
'use strict';var tnscm_adn;
(function(c,d,C){(function(){var x,A,L,J,O,M;x=function(){function m(){}function h(a,f){var b,e;if(a&&(e=a.length))for(b=0;b<e;b+=1)try{f(a[b],b,a)}catch(k){}}function g(a,f){for(var b=0,e=a.length;b<e;)if(a[b++]===f)return b-1;return-1}function n(a,f){return function(){return a.apply(f,arguments)}}function p(a,f,b){c.addEventListener?a.addEventListener(f,b,!1):c.attachEvent&&a.attachEvent("on"+f,b)}function v(a){function f(){h(v.d,function(f){f()});delete v.d}function b(){"loading"!==d.readyState&&
(f(),d.detachEvent("onreadystatechange",b))}"loading"!==d.readyState?a():v.d?v.d.push(a):(v.d=[a],d.addEventListener?d.addEventListener("DOMContentLoaded",f,!1):d.attachEvent&&d.attachEvent("onreadystatechange",b))}function q(a){function f(){for(q.time=H&&0<H.loadEventStart?new Date(H.loadEventStart):new Date;b.length;)b.shift()(q.time)}var b;q.time?a(q.time):(q.M||(q.M=[],p(c,"load",f)),b=q.M,b.push(a),"complete"===d.readyState&&f())}function y(a){var f={};a&&h(a.split("&"),function(a){a=a.split("=");
f[decodeURIComponent(a[0].toLowerCase())]=decodeURIComponent(a[1])});return f}function r(){var a=d.body,f=d.documentElement,a=a?Math.max(a.scrollHeight,a.offsetHeight,a.clientHeight):0;return Math.max(a,f.scrollHeight,f.offsetHeight,f.clientHeight)}function l(a,f){var b;return d.defaultView&&d.defaultView.getComputedStyle?(f=f.replace(/([A-Z])/g,"-$1").toLowerCase(),(b=d.defaultView.getComputedStyle(a,null))&&b.getPropertyValue(f)):a.currentStyle?a.currentStyle[f]:a.style&&a.style[f]?a.style[f]:null}
function w(a){if(!a)return{top:0,left:0};var f={top:a.offsetTop,left:a.offsetLeft};a=w(a.offsetParent);f.top+=a.top;f.left+=a.left;isNaN(f.top)&&(f.top=C);isNaN(f.left)&&(f.left=C);return f}function t(a){return a.contentDocument||a.contentWindow&&a.contentWindow.document||a.document||null}function F(a,f){for(var b=a.childNodes,e=b.length,k;e--;)if(k=F(b[e],f))return k;return f(a)}var D=["","moz","ms","webkit"],z=c.performance,H=z?z.timing:null,z=function(){if("undefined"==typeof navigator.plugins||
0==navigator.plugins.length)try{return!!new ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(a){return!1}else return navigator.plugins["Shockwave Flash"]}();return{ja:m,random:function(){var a=(new Date).valueOf().toString();return parseInt(a.substr(a.length-8,a.length))+Math.round(Math.random()*Math.pow(10,9))},X:z,trim:function(a){return String.prototype.trim!==C?String.prototype.trim.call(a):a.replace(/^\s+|\s+$/g,"")},a:h,indexOf:g,ia:function(a,f,b){var e,k;b=b||m;if(!a)return!1;k=a.length;
0===k&&b();return k?e=setInterval(function(){var g=10;do{k-=1;if(-1===k){clearInterval(e);b();break}f(a[k],k,a)}while(--g)},4):C},extend:function(a,f,b){var e,k;for(e in f)f.hasOwnProperty(e)&&(k=f[e],a[e]=b&&"function"===typeof k?n(k,a):k)},on:p,e:v,load:q,p:function(a){p(c,"scroll",a);p(c,"resize",a);a()},J:function(a,f){function b(){var b=d[k]||"visible";switch(b){case "hidden":f(b);break;default:a(b)}}var e,k;f=f||m;for(e=0;e<D.length;e++)if(k=D[e]+"VisibilityState",k=k.charAt(0).toLowerCase()+
k.substring(1),d[k]){p(d,D[e]+"visibilitychange",b);"hidden"!==d[k]&&b();return}b()},ka:y,S:function(a){function f(f){var a=!1;h(["link1","clicktag","alink1","url","adress"],function(b){f.hasOwnProperty(b)&&(a=f[b])});return a}var b,e,k=a.childNodes,g=a.parentNode,c="",d={};switch(a.nodeName){case "IMG":for(;g;){if("A"===g.nodeName){b=g.href;break}g=g.parentNode}break;case "OBJECT":h(k,function(a){"PARAM"===a.nodeName&&"flashvars"===a.getAttribute("name").toLowerCase()&&(e=a.getAttribute("value"),
d=y(e.replace(/&amp;/g,"&")),b=f(d))});break;case "EMBED":if(c=a.getAttribute("flashvars"))d=y(c.replace(/&amp;/g,"&")),b=f(d)}try{"string"===typeof b&&(b=decodeURIComponent(b))}catch(q){}return b},ga:r,$:function(a){for(var f=!1,b=a.getClientRects(),e=r(),k=b.length;k--;)if(a=b[k],0!==a.width&&0!==a.height){if(0<a.top)return a.top<=e;if(0<a.bottom)return a.bottom<=e;f=!0}return f},ha:l,V:w,B:function(a){var f={w:["paddingLeft","paddingRight","borderLeftWidth","borderRightWidth"],h:["paddingTop",
"paddingBottom","borderTopWidth","borderBottomWidth"]},b={w:a.offsetWidth,h:a.offsetHeight},e,k;for(e in b)if(b.hasOwnProperty(e)){if(0<b[e])for(k=f[e].length;k--;)b[e]-=parseInt(l(a,f[e][k]),10)||0;k=b[e]||l(a,"w"===e?"width":"height");/%/.test(k)||(b[e]=parseInt(k,10),isNaN(b[e])&&(b[e]=0))}return b},T:t,W:function(){var a=d.body,f=d.documentElement;return"number"===typeof c.pageYOffset?c.pageYOffset:f&&f.scrollTop?f.scrollTop:a&&a.scrollTop?a.scrollTop:0},Q:F,Y:function(a){try{var f=a.getAttribute("src")||
"",b=f.indexOf("//"+location.host),e;if((0!==f.indexOf("http")&&0!==f.indexOf("//")||-1<b&&8>b)&&(e=t(a))&&e.getElementById)return!0}catch(k){}return!1},t:function(a){function f(a){-1===g(excludeElements,a)&&excludeElements.push(a)}function b(a){var f=d.createElement("a");f.href=a;return f.href}var e,k,c;if(!a.tagName)return!1;if("OBJECT"===a.tagName){e=a.getAttribute("data");a=a.childNodes;if(!e)for(k=a.length;k--;)if(c=a[k],"PARAM"===c.nodeName&&"movie"===c.getAttribute("name").toLowerCase())return c.getAttribute("value");
for(k=a.length;k--;)if(c=a[k],"PARAM"===c.nodeName&&"flashvars"===c.getAttribute("name").toLowerCase()&&(c=y(c.getAttribute("value").replace(/&amp;/g,"&")),c.video1))try{return decodeURIComponent(c.video1)}catch(q){return c.video1}return e}if("VIDEO"===a.tagName){e=a.childNodes;c=e.length;var l,r;if(!a.canPlayType)return!1;for(k=0;k<c;k++)if(l=e[k],"SOURCE"===l.nodeName&&(r=l.getAttribute("type"),a.canPlayType(r)))return e=l.getAttribute("src")||!1,h(a.getElementsByTagName("embed"),f),h(a.getElementsByTagName("object"),
f),e;return e=a.getAttribute("src")}if("SVG"===a.tagName.toUpperCase())k=a.getElementsByTagName("image"),0<k.length&&(e=k[0].getAttribute("xlink:href"));else{k=(e=a.getAttribute("src"))&&"data:image"==e.substring(0,10);c=e&&(0==e.indexOf("//")||0==e.indexOf("http"));if(null==e||k)return e&&k?A.juke_host||null:null;e=a.getAttribute("src");c||(e=b(e))}return e},U:function(a){var f={};if(top!=self&&c.addonCMeter&&c.addonCMeter&&addonCMeter.currentValues&&addonCMeter.currentValues.offset){var f=d.documentElement,
b=d.getElementsByTagName("body")[0],f={w:c.innerWidth||f.clientWidth||b.clientWidth,h:c.innerHeight||f.clientHeight||b.clientHeight};return 10>=Math.abs(f.w-a.w)&&10>=Math.abs(f.h-a.h)?addonCMeter.currentValues.offset:0}return 0},l:function(){var a=A;return c.addonCMeter&&addonCMeter.config&&addonCMeter.config.region||a.region||"ua"}}}();A=function(d){var h={source:"source.mmi.bemobile.ua",juke_host:"juke.mmi.bemobile.ua/bug/pic.gif",host:"pagestat.mmi.bemobile.ua",sslhost:"sslpagestat.mmi.bemobile.ua",
err_host:"er.mmi.bemobile.ua",timer:{frequency:5,pings:[5,15,30,60,120],stop_after:5},ads:{scan_frequency:5,width:50,height:40}};d.extend(h,c.addonCMeter&&addonCMeter.config);h.custom_url&&location.host===h.custom_url.href?(h.ads.scan_frequency=h.custom_url.banner_scan_frequency,h.work_in_frame=h.custom_url.work_in_frame):h.work_in_frame=!0;return h}(x);L=function(m){function h(a,b){var e,k;for(e in b)b.hasOwnProperty(e)&&(k=b[e],a[e]=k)}function g(a){var b;try{c.XDomainRequest?(b=new c.XDomainRequest,
a&&(b.onerror=function(){a.call(null,b)})):(b=new XMLHttpRequest,a&&(b.onreadystatechange=function(){4==b.readyState&&200!=b.status&&a.call(null,b)}))}catch(e){console.error("cors:"+e)}return b}function n(a,b,e){var k="&";-1==a.indexOf("?")&&(k="?");return a+(k+b+"="+e)}function p(){for(var a=[],b=0;32>b;b++)a[b]="0123456789ABCDEF".substr(Math.floor(16*Math.random()),1);a[12]="4";a[16]="0123456789ABCDEF".substr(a[16]&3|8,1);return a.join("")}function v(a,b,e){d.cookie=a+"="+escape(b)+(e?"; expires="+
e:"")+"; path=/"}function q(a){var b=" "+d.cookie;a=" "+a+"=";var e=null,k=0,c=0;0<b.length&&(k=b.indexOf(a),-1!=k&&(k+=a.length,c=b.indexOf(";",k),-1==c&&(c=b.length),e=unescape(b.substring(k,c))));return e}function y(a){d.cookie=a+"=; expires=Thu, 01 Jan 1970 00:00:01 GMT;"}function r(){var a;try{a=d.getElementsByTagName("body")[0]}catch(b){}"undefined"!=typeof a&&null!=a||"undefined"==typeof d.body||(a=d.body);return a}var l={f:function(a,b){function e(a){k.onload=k.onerror=k.onreadystatechange=
null;b&&"function"==typeof b&&b(a)}var k=d.createElement("script"),c=d.head||d.getElementsByTagName("head")[0];h(k,{async:!0,type:"text/javascript",onload:function(){e(null)},onerror:e,onreadystatechange:function(){"loaded"!==k.readyState&&"complete"!==k.readyState||e(null)}});k.src=a;c.insertBefore(k,c.lastChild)},e:function(a){function b(){each(l.e.d,function(a){a()});delete l.e.d}function e(){"loading"!==d.readyState&&(b(),d.detachEvent("onreadystatechange",e))}"loading"!==d.readyState?a():l.e.d?
l.e.d.push(a):(l.e.d=[a],d.addEventListener?d.addEventListener("DOMContentLoaded",b,!1):d.attachEvent&&d.attachEvent("onreadystatechange",e))},ready:function(a){l.e(a)}};c.idCoreOnReady=function(f){a.onFlashReady(f)};c.tnsOnStatResult=function(a){console.log("result:"+a.result+" pid:"+a.la+" e.id: "+a.id)};var w;try{w="localStorage"in c&&null!==c.localStorage}catch(t){w=!1}var F=function(){if("undefined"==typeof navigator.plugins||0==navigator.plugins.length)try{return!!new ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(a){return!1}else return navigator.plugins["Shockwave Flash"]}(),
D=/MSIE/.test(navigator.userAgent),z=function(){var a=navigator.cookieEnabled?!0:!1;"undefined"!=typeof navigator.cookieEnabled||a||(d.cookie="testcookie",a=-1!=d.cookie.indexOf("testcookie")?!0:!1,y("testcookie"));return a}(),H=function(){var a="l";F?a="b":c.postMessage&&(w||z)?a="d":0==w&&0==z&&(a="g");try{if(c.chrome)for(var b in navigator.plugins)if(/PepperFlashPlayer/gi.test(navigator.plugins[b].filename)){a="c";break}}catch(e){console.warn("chrome : PepperFlashPlayer - has some error")}return a}(),
a=function(){function a(){function b(){try{(new CrossDomainStorage(N,"/id-core/1.77-r59654/id.html")).requestValue(u.id,function(a,b){E(b)})}catch(a){console.error("cds.js:"+a),s=p(),E(s)}}"undefined"===typeof CrossDomainStorage?l.f(G+"/id-core/1.77-r59654/cds.js",b):b()}function b(){var a=new Date;a.setFullYear(a.getFullYear()+1);v(u.wasMigrated,!0,a.toUTCString());E(s)}function e(){return q(u.wasMigrated)?!1:z&&q(u.wasInitialized)?(s=q(u.id),w?(l.f(G+"/id-core/1.77-r59654/cds.js",function(){try{(new CrossDomainStorage(N,
"/id-core/1.77-r59654/id.html")).requestValue(u.id+":"+s,function(a,e){e!=s?console.error("id: "+e+" != "+s):b()})}catch(a){console.error("migrate:"+a)}}),y(u.id),y(u.wasInitialized)):F&&(c.tns_uid=s,l.f(G+"/id-core/1.77-r59654/flash.js",function(){b()})),!0):!1}function k(){A=!0;e()||(w?(s=localStorage.getItem(u.id))?E(s):c.postMessage&&!c.JSON&&c.localStorage?l.f(G+"/json2.min.js",function(){r()?a():l.ready(function(){a()})}):c.postMessage&&c.JSON&&c.localStorage?r()?a():l.ready(function(){a()}):
E(p()):F?r()?l.f(G+"/id-core/1.77-r59654/flash.js"):l.ready(function(){l.f(G+"/id-core/1.77-r59654/flash.js")}):((s=q(u.id))||(s=p()),E(s)))}function h(){for(var a in B)if(B.hasOwnProperty(a)){var b=B[a].url,e=B[a].params,f=B[a].time,c=B[a].type,k=B[a].onError;/^POST$/gi.test(c)?Q(b,e,f,k):t(b,e,f,c,k)}B=[];for(var g in I)I.hasOwnProperty(g)&&I[g].call(this,s);I=[]}function E(a){s=a;if(w)localStorage.setItem(u.id,a);else if(z){var b=new Date;b.setFullYear(b.getFullYear()+1);v(u.id,a,b.toGMTString());
v(u.wasInitialized,!0,b.toGMTString())}K=!0;h();w?localStorage.getItem(u.flag)||((new Image).src=location.protocol+"//"+x+"?uid="+a+"&time="+(new Date).valueOf(),localStorage.setItem(u.flag,"true")):z&&!q(u.flag)&&(b=new Date,b.setFullYear(b.getFullYear()+1),v(u.flag,"true",b.toGMTString()),(new Image).src=location.protocol+"//"+x+"?uid="+a+"&time="+(new Date).valueOf())}function P(a,b){var e,f;if(b instanceof Array)for(e in b)a=n(a,b[e].key,b[e].value);else for(f in b)a=n(a,f,b[f]);return a}function Q(a,
b,e,f){try{var c=g(f);c.open("POST",a,!0);b||(b={});b instanceof Array?(b.push({key:"cookie",value:s}),b.push({key:"time",value:e?e:(new Date).valueOf()})):(b.cookie=s,b.time=e?e:(new Date).valueOf());D?c.contentType="text/plain":c.setRequestHeader("Content-type","application/x-www-form-urlencoded;charset=UTF-8");var k=P("?",b).replace(/^\?/,"");c.send(k)}catch(h){console.error(h)}}function t(a,b,e,f,k){b||(b={});a=n(a,"cookie",s);a=n(a,"time",e?e:(new Date).valueOf());a=P(a,b);try{if(f&&"JSONP"==
f||c.opera&&!("withCredentials"in new XMLHttpRequest)){var h=d.createElement("script");h.setAttribute("src",a);d.getElementsByTagName("head")[0].appendChild(h)}else{var l=g(k);l.open("GET",a,!0);0==D&&l.setRequestHeader("Accept","application/json");l.send()}}catch(q){console.log(q)}}var K=!1,N=location.protocol+"//"+(m.source||"source.mmi.bemobile.ua"),G=c.addonCMeter&&addonCMeter.hostAddon||N,C="1.77-r59654".replace(/-r\d+$/,""),x="juke.mmi.bemobile.ua/bug/pic.gif";try{m&&m.aa&&(x=m.aa)}catch(R){console.warn(R)}var u=
{id:"vplayer_user_id",wasInitialized:"tns_was_initialized",wasMigrated:"tns_was_migrated",flag:"flag"},A=!1,B=[],s="",I=[];return{init:function(){0==A?z&&!q(u.wasMigrated)?r()?k():l.ready(function(){k()}):k():K&&h()},send:function(a,b,e,f){b||(b={});b.vt=H;var c=(new Date).valueOf();K?/^POST$/gi.test(e)?Q(a,b,c,f):t(a,b,c,e,f):B.push({url:a,params:b,type:e,time:c,onError:f})},onFlashReady:function(a){try{var b=d.getElementById("div_holder");b.parentNode.removeChild(b)}catch(e){}swfobjectlite=null;
E(a)},addOnReadyListener:function(a){I.push(a)},isReady:function(){return K},getId:function(){return s},version:function(){return C}}}();c.IDCore=c.IDCore||a;a.init();return a}(A);J=function(d){function h(c,h){g[c]||(g[c]=[]);g[c].push(h)}var g={};return{ma:g,c:function(n,p){c.cm_events&&c.cm_events.join?d.a(c.cm_events,function(g,d){g&&g.event==n&&(h(n,g.callback),delete c.cm_events[d])}):c.cm_events=[];d.a(g[n],function(c){p=c.call(this,p)});return p},on:h}}(x);O=function(m,h,g,n){function p(d,
p){var r=this,l=top!==self;h.on(c,"beforeunload",function(){r.fa=!0});2<=arguments.length&&h.extend(this,p,!0);this.b=this.b||[];this.b[0]="~cm_"+d+"~";setTimeout(function(){function p(l){"AddonCMeterReady"===l.data&&(c.removeEventListener("message",p,!1),h.extend(n,c.addonCMeter&&addonCMeter.config),M.ca(g.c("templates:yes",[]),g.c("templates:no",[])),r.u(g.c("init_"+d)))}var m=l?"AddonCMeterFrame":"AddonCMeterMain";c.localStorage&&"initializing"===localStorage.getItem(m)||c.sessionStorage&&"initializing"===
sessionStorage.getItem(m)||c.sessionStorage&&"initializing"===sessionStorage.getItem("AddonCMeter")?c.addEventListener("message",p,!1):r.u(g.c("init_"+d))},20)}var v="3.4.179_"+h.l()+"/"+m.version();h.extend(p.prototype,{C:"GET",origin:location.protocol+"//"+("https:"===location.protocol?n.sslhost:n.host),ea:h.random(),da:function(){return c.addonCMeter&&addonCMeter.currentValues&&addonCMeter.currentValues.sid||this.ea},R:function(){var g={location:encodeURIComponent(c.location.href),referrer:encodeURIComponent(this.referrer||
d.referrer),is_flash:h.X?"1":"0",session_id:this.da(),version:v,sw:screen.width,sh:screen.height,scd:screen.colorDepth};screen.pixelDepth&&(g.spd=screen.pixelDepth);c.addonCMeter&&addonCMeter.PLID&&(g.tnscm_plid=addonCMeter.PLID);c.tnscm_cat&&(g.tnscm_cat=tnscm_cat);tnscm_adn&&(g.tnscm_adn=tnscm_adn);c.tnscm_pak&&(g.tnscm_pak=tnscm_pak);return g},send:function(){this.I?this.I():this.k()},k:function(){var c=0,d,r={},l=[];h.extend(r,this.R());for(h.extend(l,this.b);l.length;)if(c+=1,(d=l.shift())||
0===d)r["param"+c]=d;h.extend(r,l);m.send(this.url,g.c("send",r),this.C)}});h.extend(p.prototype,{url:p.prototype.origin+"/pagestat/PageStatEntry"});return p}(L,x,J,A);M=function(m,h){function g(c){var g=this,d=["w","h"],h=["src"];this.h=this.w=null;m.a(c,function(c){var l,p=parseInt(c,10);if(!isNaN(p))l=d.shift();else if(c instanceof RegExp||"RegExp"==c.constructor.name)l=h.shift(),p=c;l&&(g[l]=p)});this.src||!this.w&&!this.h||(this.src=/./)}var n={};m.extend(g,{j:function(d){var h=!0,q=!1,n={P:[],
current:[]};m.a(d,function(d){d instanceof RegExp||"RegExp"==d.constructor.name?h=q=d.test(c.location.host):h&&!q?n.P.push(new g(d)):h&&q&&n.current.push(new g(d))});return n},embeds:function(c){var g=[],h=[],n=[];c=c||d;m.a(c.getElementsByTagName("embed"),function(c){for(var d=c.parentNode;d;){if("OBJECT"===d.nodeName){h.push(d);break}d=d.parentNode}-1===m.indexOf(n,c)&&g.push(c)});m.a(c.getElementsByTagName("object"),function(c){-1===m.indexOf(h,c)&&-1===m.indexOf(n,c)&&g.push(c)});return g},g:function(c){function g(c,
d){m.a(n.r[c],function(c){c.check(d[0],d[1],d[2])&&(h=!0)});h&&m.a(n.G[c],function(c){c.check(d[0],d[1],d[2])&&(h=!1)})}var d=[],h,r;m.a(c,function(c,m){h=!1;for(r in n.r)n.r.hasOwnProperty(r)&&g(r,c);h&&d.push(m)});return d}});m.extend(g.prototype,{check:function(c,d,g){return this.src&&!this.src.test(c)||this.w&&this.w!==d||this.h&&this.h!==g?!1:!0}});setTimeout(function(){n.r=g.j(h.c("templates:yes",[[/banner\.volynnews\.com/i],[/\.googlesyndication\.com\/simgad\//i],[/weborama\.fr\//i],[/ads\.locals\.md\//i],
[/numbers\.md/i],[/\.zingan\.com\//i],[/cdn\.epom\.com\//i],[/trkmedia\.ollcdn\.net\//i],[/\.vcdn\.biz\//i],[/\.rontar\.com\//i],[/adfox\.ru\//i],[/sourcefabric\.net\//i],[/media\.adrcdn\.com\/ads\//i],[/c8\.net\.ua\//i],[/\.adocean\.pl\//i],[/static\..*\.kcdn\.kz\//i],[/base\.kiwi\.kz\//i],[/dotua\.org\//i],[/advideo\.com\.ua\//i],[/admixer\.net/i],[234,200],[205,333],[205,280],[205,60],[203,70],[950,90],[760,90],[730,60],[730,90],[728,90],[640,90],[500,100],[468,120],[468,60],[320,76],[320,60],
[300,600],[300,250],[300,240],[285,130],[250,250],[240,400],[240,350],[240,200],[240,90],[234,60],[230,90],[230,60],[180,150],[160,600],[160,60],[150,60],[120,600],[120,240],[120,60],[/adriver\.ru/i],[/bannerka\.ua/i],[/reclama\./i],[/bbn\.img\.com\.ua/i],[/images\.rambler\.ru\/upl\//i],[/\/images\/.*\/.*\/.*\/.*300x250\./i],[/baner\./i],[/ad.*\.bigmir\.net/i],[/\/banners_files\/.*\./i],[/b\.ex\.ua\/.*\/.*\.swf/i],[/\/openx\/www\/images\/.*\./i],[/\/bnr\//i],[/\/adban\/.*\/.*\/.*\./i],[/informers\.sinoptik\.ua/i],
[/adnet\.com\.ua\/banners\/.*\/.*\/.*\/.*\./i],[/rose\.ixbt\.com/i],[/\/adv\//i],[/i\.holder\.com\.ua\/.*\/.*\/.*\/.*\./i],[/\/images\/.*\/.*\/.*\/.*\.swf$/i],/\.kz/,[728,200],[/\/banners/i],/allfun\.md/,[295,295],[476,102],/alltravel\.md/,[168,138],[215,155],[210,138],[394,88],/odessa-life\.od\.ua/,[/\/banners\//i],/volynnews\.com/,[460,145],[220,180],/moldova\.org/,[301,301],/tsamali\.ge/,[580,100],/i.*p.*n.*\.ge/,[/\/www\/images\/.*\./i],/forum\.ge/,[240,50],/file\.ge/,[/\/ad.*\./i],/\.ge/,[/\/www\/images\//i],
[/baner/i],[/banner/i],[640,100],/\.md/,[/\/banner/i],/mail\.ru/,[/r\.mradx\.net\//i,300,300],[/r.*\.mail\.ru\/b.*\.gif$/i],[/r.*\.mail\.ru\/b.*\.png$/i],[/r.*\.mail\.ru\/b.*\.jpg$/i],[/r.*\.mail\.ru\/b.*\.swf$/i],[/promoblocks\.ru/i],/football\.ua/,[/spadsmedia\.com\/www\/delivery\/afr\.php\//i],[/sportingbet\.host\.bannerflow\.com\//i],/total\.kz/,[1E3,115],[/\/gb\.php..*=/i],/namba\.net/,[468,90],[1E3,90],[200,350],/besplatka\.ua/,[300,300],[660,90],/nur\.kz/,[/\/advert\//i],/magnolia-tv\.com/,
[668,60],[300,100],[/\/files\/ban\//i],[100,100],/blogas\.lt/,[/static-system\.adtarget\.me\//i],[/banners\.adnet.*\.lt\//i],[980,200],[750,200],[980,180],/companion\.ua\//,[960,90],/172\.16\.0\./,[/\.gif/i],[/\.png/i],[/\.swf/i],[/\.jpeg/i],[/\.jpg/i],/ex\.ua/,[/ad_click/i],/aviso\.ua/,[/banner\.ool\.ua\//i]]))},4);setTimeout(function(){n.G=g.j(h.c("templates:no",[[/old\.amindi\.ge\/city\//i],[/myvideo\.ge\/movies\//i],[/site-analytics\.info\//i],[/algovid\.com\//i],[/agitated\.ru\//i],[/quentina\.ru\//i],
[/maps\.googleapis\.com\//i],[/servplay\.net\//i],[/a\.c8\.net\.ua\/.*frame\.php/i],[/\.admixer\.net\/test1\/.*\/\..someClick=/i],[/orion-site\.com\/ajax/i],[/mwayss\.com\/ads/i],[/laredoute\.com\/products\//i],[/newstok\.ru\//i],[/anarrma\.ru\//i],[/gvt1\.com\//i],[/avalln\.ru\//i],[/ecpmrocks\.com\//i],[/ainulindal\.ru\//i],[/anghabar\.ru\//i],[/e-protected\.ru\//i],[/ad5ve\.com\//i],[/socauth\.privatbank\.ua\//i],[/atemda\.com\//i],[/atmsrv\.com\//i],[/meta\.vcdn\.biz\/.*_megogo/i],[/dotua\.org\/player\.js/i],
[/cdn\.vm-corporate\.com\//i],[/xl415\.com\//i],[/ad-maven\.com\//i],[/rev2pub\..*com\//i],[/tmdn.*\.com\//i],[/vindicosuite\.com\//i],[/telephone-store\.ru\//i],[/admtpmp.*\.com\//i],[/media\.adk2x\.com\//i],[/wheelpath\.com\//i],[/tools\.freehost\.com\.ua\//i],[/login\.snw\.media\//i],[/gocash01\.net\//i],[/akamai.*\.net\//i],[/clike\.su\//i],[/mtagmonetizationb\.com\//i],[/rafomedia\.com\//i],[/9f6qmf0hs\.ru\//i],[/cpmaffiliation\.com\//i],[/regiepublicitairecpm\.com\//i],[/cpmad.*\.com\//i],[/admediacpm\.com\//i],
[/adserve/i],[/prd.*\.rontar\.com\/productiframe\.axd/i],[/ato\.mx\//i],[/trafficmonsoon\.com\//i],[/\.com\/t\.php.*a=96/i],[/\.ua\/delivery\/afr\.php/i],[/rvfrm2010\.com\//i],[/touch1\.ru\//i],[/dataffastguru\.info\//i],[/playitviral\.com\//i],[/avenue\.center\//i],[/imgsrv\.io\//i],[/srv-statistics\.com\//i],[/cptlsrv\.com\//i],[/adsrvmedia\.net\//i],[/atdmt\.com\//i],[/wntg2x\.com\//i],[/memeglobal\.com\//i],[162,228],[/w55c\.net\//i],[/pipesarcade\.com\//i],[/groovitdigital\.com\//i],[/coolad9\.com\//i],
[/blkz2x\.com\//i],[/servd2wn\.com\//i],[/yieldmedia\.net\//i],[/pagead2\.googlesyndication\.com\/pagead\/ads/i],[/adv679854\.ru\//i],[/semantichelper\.com\//i],[/connect\.ok\.ru\//i],[/bidvertiser\.com\//i],[/lightquartrate\.com\//i],[/8838d3aa4a6\.com\//i],[/secure\..*trk.*\.com\//i],[/r3\.c8\.net\.ua\/match_dsp\.php/i],[/delivery\.promo\.ge\//i],[/connexity\.net\//i],[/ad131m\.com\//i],[/merchenta\.com\//i],[/yu0123456\.com\//i],[/a4b80300d1f45b09e416e0934d52e2a2539\.com\//i],[/cured\.com\//i],
[/wtp101\.com\//i],[/trk-xzz\.com\//i],[/de17a\.com\//i],[/getsecureweb\.com\//i],[/tesel8\.com\//i],[/everesttech\.net\//i],[/imrk\.net\//i],[/h\.holder\.com\.ua\/f/i],[/starkcom\.net\/srv/i],[/r.*\.c8\.net\.ua\/getiframe\.php/i],[/localpages\.com\//i],[/leisure\.com\//i],[/tvi\.ua\/adsense\/banner.*\.html\//i],[/teracreative\.com\//i],[/rernd\.com\//i],[/pheasantissueflummery/i],[/revsci\.net\//i],[/rtbidder\.net\//i],[/mediasoul\.net\//i],[/inb\.genorithm\.com\//i],[/\/image.*\/upload.*\//i],[/product.*picture/i],
[/goo\.mx\//i],[330,220],[/kapcha/i],[/\.ria\..*\/photos\//i],[/img\/article\//i],[/design\.vesti-ukr\.com\//i],[/img\.com\//i],[/^http:\/\/undefined/i],[/linkis\.com\//i],[/magnetix\..*\//i],[/ipvertising\.com\//i],[/shop_image/i],[/fotos\..*\/images\//i],[/sfera-tv\.com\.ua\/.*img\//i],[/ukrinform\.ua\/cgi-bin\//i],[/unian\..*\/cgi-bin\//i],[/iqalhcxcqz\.ru\//i],[/ritorno\.ru\//i],[/kleopatra0707\.com\//i],[/107\.23\..*\..*\//i],[/otzovik\.com\/product\//i],[/ftop\.ru\//i],[/osvita\.ua\/.*image/i],
[/adroll\.com\//i],[/showbiza\.com\/.*photo/i],[/utro\.ua\/static\/adsense\//i],[/ikea\.com\//i],[/2mdn\.net\//i],[/easyhits4u\.com\//i],[/img\.4mama\.com\.ua\//i],[/websteroidsapp\.com\//i],[/\.websearch\./i],[/searchsupporter\.info\//i],[/infoseekerapp/i],[/lookforithere\.info\//i],[/click2dad\.net\//i],[/aceadsys\.net\//i],[/bidswitch\.net\//i],[/targetix\.net\//i],[/people-group\.su\//i],[/mynagor\.com\//i],[/\.am15\.net\//i],[/fsua_items\/screen\//i],[/orbit\.lun\.ua\//i],[/google\.com\.ua\//i],
[/hotline\.ua\/price\//i],[/all\.biz\/img\/.*\/catalog\/.*\./i],[/nxnxcaqicm/i],[/apis\.google\.com\//i],[/rmbn\.net\//i],[/adone\.ru\//i],[/advertbox\.us\//i],[/quikdisplay\.com\//i],[/thespatialists\.com\//i],[/adimps-perf\.com\//i],[/tooljava\.org\//i],[/gettvwizard\.com\//i],[/mybb\.ru\//i],[/lollipop-network\.com\//i],[/playblasteroids\.com\//i],[/rbc\.ua\/static\//i],[/static\.com\//i],[/dumedia\.ru\//i],[/ticket\.net\//i],[/hoptopboy\.com\//i],[/porn\..*com\//i],[/kvihit\.com\//i],[/imagevenue\.com\//i],
[/obrona\.org\//i],[/null$/i],[/interakt\.md\/content/i],[/gwallet\.com\//i],[/predictormedia\.com\//i],[/img\.ubr\.ua\/banners\/.*adsense\./i],[/dotomi\.com\//i],[/mobileadhost\.com\//i],[/adsoptimizer\.net\//i],[/ad-sys\.com\//i],[/drivesection\.net\//i],[/tooldiv\.net\//i],[/livexjs\.net\//i],[/fellabooks\.net.*\/$/i],[/chocolatemx\.net\//i],[/aspire-guitar\.com\//i],[/golinkon\.info\//i],[/perfectnavigator\.com\//i],[/googleads/i],[/\.host\.bannerflow\.com\//i],[/serving.*\.com\//i],[/tracking\.m6r\.eu\//i],
[/upload.*\/articles\//i],[/zedo\.com\//i],[/gogorithm\.com\//i],[/pdmayt\.com\//i],[/metrigo\.com\//i],[/vdaqyqwsrd\.ru\//i],[/qrdeom\.com\//i],[/tatami-solutions\.com\//i],[/cloudfront\.net\//i],[/mrlmedia\.net\//i],[/mothernist\.hiro\.tv\//i],[/\.wlboon\.com\//i],[/admetaserver\.com\//i],[/\.ru\/show_banner\//i],[/tags\.qservz\.com\//i],[/neomion\.com\//i],[/^http:\/\/54\./i],[/x\.abk954\.com/i],[/creative\.xtendmedia\.com\//i],[/statisticsreporting\.com\//i],[/imhonet\.ru\/element\//i],[/mailsmania\.ru\//i],
[/romilit\.com\//i],[/proligtb\.com\//i],[/brucelead\.com\//i],[/exebid\.ru\//i],[/koluty\.com\//i],[/\.retark\.com\//i],[/com\.adv\.vz\.ru\//i],[/webmoney\.ua\/tools\//i],[/weropiy\.com\//i],[/\/games\/img\//i],[/flashgames.*\..*\//i],[/games\.info\//i],[/maikaru\.ru\/picture\//i],[/zvek\.com\.ua\/images\//i],[/get_qrapi/i],[/grandcapital\.ru\/static\/img/i],[/creativecdn\.com\//i],[/greefl\.com\//i],[/\.jutulep\.com\//i],[/baseflash\.com\//i],[/media\.tumblr\.com\//i],[/ssp\.adriver\.ru\/cgi-bin\/sync\.cgi/i],
[/tractionize\.com\//i],[/secure\.demand-go\.com\//i],[/yourbucks\.org\//i],[/datamind\.ru\//i],[/fresh-cup\.org\//i],[/ad\.starlightmedia\.ua\//i],[/financecontext\.ru\//i],[/attiveri\.com\/.* $/i],[/youtube\.com\//i],[/meta\.ua\/cell\.php/i],[/paramedjo\.com\//i],[/intencysrv\.com\//i],[/kilopog\.com\//i],[/gravyseals\.com\//i],[/media6degrees\.com\//i],[/lokomusic\.com\//i],[/tisa.ama\.com\/banner\.php/i],[/ministerial5\.com\//i],[/admailtiser\.com\//i],[/adgorithms\.com\//i],[/\/media\/gallery\//i],
[/\.dotua\.org\/.*\/cover\/.*\.jpg$/i],[/wp-content\/upload/i],[/netdna-cdn\.com\//i],[/\/logo/i],[/adsmile\.biz\//i],[/medads\.ru\//i],[/gittigidiyor\.com\//i],[/oneund\.com\//i],[/xmasdom\.com\//i],[/rainoftraffic\.info\//i],[/1xbet\.com\//i],[/clkrev\.com\//i],[/pub-fit\.com\//i],[/clicksor\.com\//i],[/sendspace\.com\//i],[/pgssl\.com\//i],[/rutarget\.ru\//i],[/datropy\.com\//i],[/dolka\.ru\//i],[/batanga\.net\//i],[/adorika\.net\//i],[/rfihub\.com\//i],[/loponop\.com\//i],[/palgames\.info\//i],
[/play882\.info\//i],[/medialand\.ru\//i],[/funnygamezer\.info\//i],[/cloudgamezer\.com\//i],[/utrehter\.com\//i],[/hopto\.me\//i],[/intag\.co\/.* $/i],[/adk2\.com\//i],[/img\.admaster\.net\//i],[/openx\.net\//i],[/firstadvplug\.com\//i],[/pirrit\.com\//i],[/metka\.ru\//i],[/tomobol\.com\//i],[/adzoook\.com\//i],[/adservingfree\.info\//i],[/drgo\.ru\//i],[/slopty\.ru\//i],[/tradedoubler\.com\//i],[/fastloca\.com\//i],[/hide4you\.com\//i],[/proxy\.net\//i],[/bannerhost\.ru\//i],[/bannercity\.ru\//i],
[/m2pub\.com\//i],[/theseaapp\.com\//i],[/holisticmedicalwellness\.com\//i],[/qonenoj\.ru\//i],[/amazonaws\.com\//i],[/ipicture\.ru\/uploads\//i],[/reacten\.com\//i],[/thinglink\.me\//i],[/ad\.mail\.ru\/adi\//i],[/k8media\.com\//i],[/notificatoin\.com\//i],[/co-co-co\.co\//i],[/\.dd34\.ru\//i],[/screenshot/i],[/yidop\.com\//i],[/pokitom\.com\//i],[/perfectmoney\.is\//i],[/20dollars2surf\.com\//i],[/bet-at-home\.com\//i],[/\.derploime\.com\//i],[/\.nekki\.ru\/banner\.php/i],[/tlvmedia\.com\//i],[/yoz5\.info\//i],
[/game.*\.info\//i],[/jumbaexchange\.com\//i],[/media-servers\.net\//i],[/gnezdo\.ru\//i],[/quelliclub\.ru\/slider\//i],[/azd3\.info\//i],[/26sec\.com\//i],[/magicplayer\.torrentstream\.org\//i],[/refban\.com\//i],[/microads\.ru\//i],[/scanmedios\.com\//i],[/trkclk\.net\//i],[/game.*\.com\//i],[/ro2\.biz\/ad\.php/i],[/gmodules\.com\//i],[/bremdy\.ru\//i],[/biglu\.ru\//i],[/pricora\.com\//i],[/twitbridge\.com\//i],[/resultsaccelerator\.net\//i],[/gayua\.com\//i],[/okitspace\.com\//i],[/yottos\.com\//i],
[/teaserjs\.info\//i],[/wambacdn\.net\//i],[/adultadworld\.com\//i],[/adnetworkme\.com\//i],[/seethisinaction\.com\//i],[/cameleo\.ru\//i],[/exoclick\.com\//i],[/\.rubiconproject\.com\//i],[/\.adnetwork.*\.net\//i],[/mediads\.info\//i],[/\.zanox\.com\//i],[/\.abnad\.net/i],[/reachjunction\.com\//i],[/\.e-viral\.com\//i],[/\.traffichaus\.com\//i],[/\.cmle\.ru\//i],[/datam\.com\//i],[/improvemedianetwork\.com\//i],[/adxplosions\.com\//i],[/mediaplex\.com\//i],[/redintelligence\.net\/request_content\.php/i],
[/baserve\.net\/serve\.php/i],[/ktbt\.ru\/b\.php/i],[/sociomantic\.com\//i],[/yangot\.com\//i],[/static.*\.rutracker\.org\/iframe/i],[/partners\.otpusk\.com\/media\.php/i],[/image\.tsn\.ua\/media\/images/i],[/nepalon\.com\//i],[/\.56.*\.net\/.*2\.php/i],[/\/vast\.php/i],[/ad.*\.adkserve\.com\//i],[/s\.holder\.com\.ua\/s/i],[/\.avazu\.net\//i],[/media\.glispa\.com\//i],[/squirrelsigdrs\.in\//i],[/overridingnichts\.in\//i],[/tecontx\.com\//i],[/ad-srvr\.com\//i],[/pswec\.com\//i],[/hubrus\.com\//i],
[/beatwaretranscribing\.in\//i],[/ads\.people-group\.net/i],[/holyclick\.ru/i],[/\.bidsystem\.com/i],[/zpk200\.com\/serve/i],[/imgads\..*\.net\/afr\.php/i],[/\.btricl3\.ru\/js\/rot\.php/i],[/\.tizerbank\.com\//i],[/\.plomihy\.com/i],[/static\.adv.*\.ru\/banners\//i],[/meta\.ua\/f_new\.asp/i],[/bdv\.bidvertiser\.com\/bidvertiser\.dbm/i],[/squirrelsigdrs\.in\/banners\/show\.php/i],[/code\.gif/i],[/calend\.ru\/img\/calendar\//i],[/hochu\.ua\/images\/articles\//i],[/tagcloud\.swf/i],[/myinfotopia\.com\//i],
[/swfhttprequest\.swf/i],[/cityads\.ru\//i],[/\/www\/delivery\//i],[/z5x\.net\//i],[/adotube\.com\//i],[/lux-bn\.com\.ua\//i],[/criteo\.com\//i],[/autocompleteplus\.com\//i],[/etgdta\.com/i],[/soundmanager.*\.swf/i],[/player\.swf/i],[/img\.traffim\.com\//i],[/sharedaddomain\.com\//i],[/avalala\.com\//i],[/meta\.ua\/img\/b\/roll_flv2\.swf/i],[/flowplayer/i],[/manifest\.f4m/i],[/radikal\.ru\//i],[/jsonlock\.net\//i],[/medbrowse\.com\.ua\/oops/i],[/\.yandex\./i],[/proxy\.com/i],[/ternopilmarket\.net\/modules\/goods\/images\//i],
[/proxy.*\.media\.online\.ua\//i],[/\/picture.*_user\//i],[/img.*\.begun\.ru\//i],[/topdownloads\.ru\//i],[/gloker\.org\/upload/i],[/e-parfum\.in\.ua\/products_image\//i],[/mycdn\.me\//i],[/gallery\.ru\//i],[/adxpansion\.com\//i],[/creoads\.com\//i],[/bm\.img\.com\.ua\//i],[/a\.s3\.ua\//i],[/servedbyadbutler\.com/i],[/kidstaff\.net/i],[/counter\.png/i],[100,100],[/\/widget.*\//i],[/lh.*\.ggpht\.com\//i],[/mathtag\.com/i],[/kavanga\.ru/i],[/anonymizer\.com\.ua/i],[/\.adnxs\.com/i],[/\.yadro\.ru/i],
[/\/img.*\/photo.*\//i],[/\/foto\//i],[/odnoklassniki\./i],[/static\/images/i],[/\.vk\.me\//i],[/rollingstone\.com\//i],[/\/interview.*\//i],[/\/post.*\//i],[/ads.*\.contentabc\.com\//i],[/ads.*\.msn\.com\//i],[/ads\.webmasters\.ru\//i],[/ads\.vsisumy\.com\//i],[/ads\.trk4\.com\//i],[/ads\.trafficjunky\.net\//i],[/files\/images/i],[/ads\.porn.*\//i],[/4baby\.ua\/pictures/i],[/\.de\//i],[/\/thumb.*\//i],[/ad\.drugasmuga\.com\/ban\.php/i],[/\/public\/images\/gallery\//i],[/imgn\.dt00\.net\//i],[/lcads\.ru\//i],
[/gazzete\.mk\.ua\/wp-content\/uploads\//i],[/techniks\.mk\.ua\/wp-content\/uploads\//i],[/img\.terrikon\.info\//i],[/optimizedby\.brealtime\.com\//i],[/\/uploads\/posts/i],[/source\.mmi\.bemobile\.ua\/video\//i],[/avatar/i],[/\.pcads\.ru\//i],[78,78],[/uploads\.ru\//i],[88,40],[/fliphotos\.com\//i],[/rand_img\.php/i],[/\/images_slandocomua\//i],[/chrome-extension:/i],[/about:blank/i],[/data:/i],[/gazeta\.ua\/img\/preview\//i],[/www\.ex\.ua\/show\//i],[/img\.gad\.org\.ua/i],[/1x1\.gif/i],[/vk\.jpg/i],
[/c\.bigmir\.net/i],[/adlesse\.com/i],[/turzona\.com\.ua/i],[/kartinka\.com\.ua/i],[/totoro\.com\.ua/i],[/tas-ua\.toboads\.com/i],[/vk\.com/i],[/infrm\.weather\.ua\/image\//i],[/vk_banner/i],[/\.doubleclick\.net/i],[/twitter\.com/i],[/facebook\.com/i],[/captcha/i],[/images\.mob\.ua\//i],[/gorgeoushandbag\.com\//i],[/imgg\.dt0.*\.net\//i],[/banner\.ua\/cgi-bin\/core\.fcgi/i],[/adverserve\.net/i],[/yield.*\.com\//i],[/tbn\.ru/i],[/adv\.fraza\.ua\//i],[/sinoptik\.ua\/_uploaded_files\/..\/..\/uft_................................\.jpg$/i],
[/liga\.net\/www\/images\/.*\./i],[/x\.magnet\.kiev\.ua\/www\/images\/.*\./i],[/ads.*\.com\//i],/hostinghost14\.com\//,[/^$/i],/myauto\.ge/,[/banners\//i],/timpul\.md/,[150,60],/tvmr\.ge/,[/components\/images\/banner.*\.gif$/i],/hotline\.ua/,[/\/img\/tx\//i],[120,60],/bona\.ua/,[/data\/small\//i],/kriminal\.tv/,[/image/i],/\.kz/,[/\/i\/0.*\.gif/i],/krisha\.kz/,[/\/i\/pro\//i],[70,50],[120,90],[60,50],/kolesa\.kz/,[60,50],[/\/idrive\//i],[/\/uploads\/content\//i],/magnolia-tv\.com/,[/pictures\/avatar\//i],
/infohome\.com\.ua/,[250,250],/auto\.mail\.ru/,[/r.*\.mail\.ru\/b.*\.jpg$/i],/sport\.ua/,[/sport\.ua\/images\//i],/autocentre\.ua/,[/autocentre\.ua\/images\//i],/terrikon\.com/,[/\/fans\//i],/kievskaya\.com\.ua/,[/image\.tsn\.ua\//i],/mbox2\.i\.ua/,[/fsimg\.ru\//i],/uaua\.info/,[/\/pictures\//i],/telekritika\.ua/,[/telekritika\.ua.*\/imgs\//i],[/telekritika\.ua.*\/images\//i],/meteo\.ua/,[/meteo\.ua\/var\/banners\/favorites_ua\.jpg/i],/smartphone\.ua/,[/smartphone\.ua\/img\//i],[240,400],/itc\.ua/,
[/itc\.ua\/files\/pic/i],[/wp-content/i],/lissod\.com\.ua/,[/\/st_img\/flash\//i],/onlinetb\.com\.ua/,[200,200],/delo\.ua/,[/inf\.korrespondent\.net/i],[/informers\.ukr\.net/i],/sport-express\.ua/,[/sport-express\.ua\/img\//i],/calend\.ru/,[/promo\.1000zakazov\.ru\//i],[/shkolazhizni\.ru\/img\/adv\//i],/bestdroid\.ru/,[/upload/i],/hnb\.com\.ua/,[/artimage/i],/biathlon\.com\.ua/,[/img\/ministerstvo\.gif/i],/gazeta\.ua/,[300,240],/mamaclub\.ua/,[300,250],/myradio\.ua/,[300,250],/oceni\.ua/,[250,250],
/ava\.ua/,[240,400],/games\.bigmir\.net/,[/ads\..*\./i],/connect\.ua/,[300,240],/bilshe\.com/,[/banner/i],/realty\.mail\.ru/,[/img\.pre\.realty\.mail\.ru\/.*\.jpg$/i],/pogoda\.mail\.ru/,[/r.*\.mail\.ru\/b.*\.jpg$/i],/cards\.mail\.ru/,[/r.*\.mail\.ru\/b.*\.png$/i],/hi-tech\.mail\.ru/,[/r.*\.mail\.ru\/b.*\.png$/i],[/r.*\.mail\.ru\/b.*\.jpg$/i],/otvet\.mail\.ru/,[/r.*\.mail\.ru\/b.*\.gif$/i],/health\.mail\.ru/,[/r.*\.mail\.ru\/b.*\.gif$/i],[/r.*\.mail\.ru\/b.*\.jpg$/i],/deti\.mail\.ru/,[/r.*\.mail\.ru\/b.*\.jpg$/i],
/mail\.ru/,[/ban\./i],[/\/adv\//i]]))},4);g.ca=function(c,d){n.r=g.j(h.c("templates:yes",c));n.G=g.j(h.c("templates:no",d))};return g}(x,J);(function(m,h,g,n,p,v){var q=(m=(m=c.performance)?m.timing:null)?new Date(m.navigationStart||m.connectStart):new Date,y=navigator.userAgent,r=/android|mobi|mini|blackberry|samsung|bada|nokia|series|symb(ian|os)|playstation/i.test(y),l=!(top===self||top===c),w=location.href.replace(location.hash,"");c.__cm||(m=c.__cm=[],g.extend(m,{on:n.on}));if(-1==g.indexOf(c.__cm,
g.l())){tnscm_adn=tnscm_adn||[];0>g.indexOf(tnscm_adn,"inline_cm")&&g.Q(d,function(c){if(8===c.nodeType&&"MMI CMeter"===g.trim(c.nodeValue))return!0})&&tnscm_adn.push("inline_cm");var t=new p("banners",{n:[],q:0,D:1,u:function(){var d=/MSIE/.test(y),m=/iPhone OS 3/.test(y);if(!l||h.work_in_frame)this.C=c.opera||d||m?"GET":"POST",setInterval(function(){t.g(t.H)},1E3*h.ads.scan_frequency),this.b.sr=1,g.J(this.o,this.v),t.g(t.H)},A:function(){this.referrer=w;this.q=0;this.n=[];this.D++},o:function(){l?
this.b.sr=2:delete this.b.sr},v:function(){this.b.sr=1},g:function(l){function m(a,b){function e(a){var b,c="",f="div[class*=brending];a[class*=branding];div[id*=branding] > a;div[class*=branding] > a;a[id*=branding];a".split(";"),g=f.length;if("A"==a.tagName)return a.getAttribute("href");for(a==d.body&&(c="body >");g--;)if(b=a.querySelectorAll(c+f[g]),!(3<b.length)&&b[0])return b[0].getAttribute("href")}function f(a){var b=((a.currentStyle||c.getComputedStyle(a,null)||{}).backgroundImage||"").match(k);
b&&b[1]&&300<=a.offsetWidth&&240<=a.offsetHeight&&(b=b[1].split('"').join(""),b!=c.location.href.split("#")[0]&&n.push({node:a,bg:b,cl:e(a)}))}var h=a.childNodes||[],l=h.length,n=m.items||[],D=["head","script","style"],q;if(0>=b)p&&(q=d.getElementById("branding_wrap")||d.getElementById("html-id"))&&(p=!1,m(q,4));else{for(m.items=n;l--;)1==h[l].nodeType&&0>g.indexOf(D,h[l].tagName.toLowerCase())&&(f(h[l]),m(h[l],b-1));return m.items}}function n(a){function f(a){var c=g.t(a),d=g.B(a);d.w<=h.ads.width||
d.h<=h.ads.height||(b.push(a),e.push([c,d.w,d.h]))}function d(a){return a.addonCMeter&&a.addonCMeter.PLID?!0:!1}g.a(a.images||a.getElementsByTagName("img"),f);g.a(a.getElementsByTagName("svg"),f);g.a(a.getElementsByTagName("video"),f);g.a(v.embeds(a),f);g.a(a.getElementsByTagName("iframe"),function(a){var b,e=!1;g.Y(a)?(b=a.contentWindow||a.contentDocument.parent,b.__cm&&-1!=g.indexOf(b.__cm,g.l())||d(b)||(g.a(b.document.getElementsByTagName("script"),function(a){a=g.t(a);/source\.mmi\.bemobile\.ua\/cm\/(cmeter_an|cm)\.js/.test(a)&&
(e=!0)}),e||n(g.T(a)))):d(c)||f(a)})}var a=[],f=t.g.O=t.g.O||[],b=[],e=[],k=/\s*url\(\s*([^\)]+)\s*\)\s*/i,p=!0;-1===g.indexOf(f,l)&&f.push(l);n(d);for(g.a(v.g(e),function(c){a.push(b[c])});f.length;)f.shift()(a,m(d,4))},H:function(c,d){function h(){e=n.c("addDisappearBanner",e);e=n.c("banners",e);b.b.result=encodeURIComponent("["+e.join(",")+"]");e.length&&b.send()}function a(a,b,c,e){var f="",f='{"link":"'+a+'", "pos":"'+b;c&&(f+='", "cl":"'+c);e!=C&&(f+='", "bt":"'+e);return f+'"}'}function f(a){var b=
a.attributes.length,c;if(c=a.getAttribute("data-cmeter"))return c;for(;b--;)if("data-cmeter"==a.attributes[b].nodeName)return a.attributes[b].nodeValue}var b=this,e=[],k={},l="sent"+b.D;g.a(d,function(b){var c,d=b.bg;if(f(b.node)!==d){if("data:image/"==d.substr(0,11).toLowerCase()){if(k.hasOwnProperty(d))return;c=new Image;c.src=d;if(33>c.width&&33>c.height){k[d]=c;return}}b.node.setAttribute("data-cmeter",d||l);t.q++;e.push(a(d,0,b.cl,2));50<=e.length&&(h(),e=[])}});g.a(c,function(c){if(f(c)!==l){var d,
k=g.t(c),m=g.S(c);if(g.$(c))d=g.B(c),d=g.V(c).top+g.U(d)+d.h;else{if(-1===g.indexOf(b.n,c)){b.n.push(c);return}d=-1}c.setAttribute("data-cmeter",l);t.q++;e.push(a(k,d,m));50<=e.length&&(h(),e=[])}});h()}}),x=new p("timer",{u:function(){this.i=null;if(!l||h.work_in_frame&&!h.addon_disable_frame_timers)this.L=[],g.extend(this.L,h.timer.pings),g.load(this.K),g.p(this.p),g.J(x.o,x.v)},Z:function(){try{return c.top.__cm?(clearInterval(this.interval),!1):!0}catch(d){return!0}},I:function(){var c=new Date,
d=c-q;this.b[1]=Math.round(((this.m||c)-(this.s||q))/1E3);this.b[2]=this.i;this.b[4]=Math.round(d/1E3);if(!l||this.Z())this.k(),this.k.time=c},N:function(){var c=new Date,d=Math.round((c-this.s)/1E3),c=Math.round((c-(this.k.time||0))/1E3)>=h.timer.frequency;this.s&&c&&(d>=60*h.timer.stop_after&&clearInterval(this.interval),d>=h.timer.pings[0]?(this.send(),1===h.timer.pings.length&&(this.ba=h.timer.pings[0]-this.F),this.F=h.timer.pings.shift()):0==d%this.ba?(this.send(),this.F=d):this.b[2]!==this.i&&
this.send())},K:function(c){this.b[3]=c-q;this.p()},o:function(){var c=new Date;if(!this.m)if(this.s=c,r){var d=this;setTimeout(function(){t.q+t.n.length||d.N()},1E3*h.ads.scan_frequency+1E3)}else this.interval=setInterval(this.N,1E3),this.send()},v:function(){var c=new Date;this.m||(this.m=c,r||this.send(),clearInterval(this.interval))},p:function(){var c=d.body,h=d.documentElement,l=g.W(),a="clientHeight"in h?h.clientHeight:0;c&&(a="CSS1Compat"===d.compatMode?h.clientHeight:c.clientHeight);l+a>=
this.i&&(this.i=l+a)},A:function(){this.i=null;this.m=C;this.referrer=w;q=new Date;clearInterval(this.interval);if(!l||h.work_in_frame&&!h.addon_disable_frame_timers)g.load(this.K),this.b[3]=0,h.timer.pings=[],g.extend(h.timer.pings,this.L),this.o()}});setInterval(function(){var c=location.href.replace(location.hash,"");w!==c&&(t.A(),x.A(),w=c)},1E3*h.timer.check_location_timer||1E3);c.__cm.push(g.l())}})(L,A,x,J,O,M)})()})(window,document);
